services:
  redis:
    image: redis:7-alpine
    container_name: econiq-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: econiq-app
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      - MALLOC_ARENA_MAX=2
      - POLARS_MAX_THREADS=2
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data:
    driver: local
